package com.greenteam.spacefighters.entity.entityliving.obstacle;

public enum TileType {
	GRASS,
	SOIL,
	COLLISIONDETECTEDSOIL,
	BRICK,
	SPIKES,
	GAMEOVERSPIKES,
	PLAYER,
	REDENEMY,
	POLICEENEMY,
	GOALGATSBY,
	GOALITEMSTART,
	GOALITEMWAYPOINT,
	AIR,
	UNKNOWN
}